config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  
  get 'discover' => 'discover#index'
  post 'discover_create_post' => 'discover#create_post'
  get 'fun' => 'fun#index'

  resources :users do
    resources :users do
      member do
        post 'follow'
      end
    end
  end
  

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  has_one :avatar
  # make the user followable
  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController

  def index
    @posts = Post.last(25).reverse
    @post = Post.new
    @avatars = Avatar.all.last(25).reverse
  end

  #TODO: make the new post go into the database

  def create_post
    current_user.posts.create post_params
    redirect_to discover_path
  end

  def post_params
    params.require(:post).permit(
      :content
      )
  end

end

app/controllers/fun_controller.rb
class FunController < ApplicationController
  def index
    @posts = Post.all
    @avatars = Avatar.all
    # @avatar = avatar.find params[:user_id]
    @users = User.all
  end

private
  def post_params
    params.require(:post).permit(
      :content
      )
  end
end

private
  def avatar_params
    params.require(:avatar).permit(
      :src,
      :user_id
      )
  end

private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name
    )
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # if the user is logged in, redirect to the current user page,
    # otherwise render our marketing page
    if user_signed_in?
      @informative_text = "#{current_user.email} is signed in"
    else
      @informative_text = 'No user is singed in'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@posts = Post.all
	end

	def create
		@post = Post.create post_params
	end

	def edit
		@post = Post.find params[:id]
	end

	def show
		@post = Post.find params[:id]
	end

	def create
		@post = Post.new(post_params)
			if @post.save
				flash[:notice] = "post has been successfully saved"
				redirect_to hpost_path
			else
				flash[:error] = "post was not saved"
			end
	end

	def update
		@post = Post.find params[:id]
		@post.update(post_params)
			if @post.save
    	flash[:notice] = 'post data was successfully created.'
    	redirect_to post_path
    else
    	flash[:error] = "post data was NOT saved."
    	render :new
		end
	end

	def destroy
		@post = Post.find params[:id]
		@post.destroy
		redirect_to user_path
	end

private
	def post_params
		params.require(:post).permit(
			:content
			)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
    @subscriptions = @user.following_users
    @subscribers = @user.user_followers
    # we want posts from ourselves plus every user to whom we are
    # subscribed
    poster_ids = [params[:id]] + @subscriptions.map(&:id)
    @posts = Post.where(user_id: poster_ids).order('created_at desc')
  end

  def follow
    @follower = User.find params[:user_id]
    @followed = User.find params[:id]
    @follower.follow(@followed)
    flash[:notice] = "Following #{@followed.first_name} #{@followed.last_name}"
    redirect_to :back
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = user.find params[:id]
    @user.update_attributes user_params
    # redirect_to user_path(@user)
  end

  def destroy
    @user = user.find params[:id]
    @user.delete
    # redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discover_helper.rb
module DiscoverHelper
  def recent_posts(num_posts)
    Post.find(:all, :order => "created_at desc", :limit => num_posts)
  end
end

app/helpers/fun_helper.rb
module FunHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/discover/index.html.haml
/ TODO: fix form_for nil class error - SUBMIT TO DB

-if user_signed_in?
  %h3 Enter a New Post here!
  = form_for @post, url: discover_create_post_path do |f|
    = f.label :Content
    = f.text_field :content
    = f.submit

%h3 All Fumblr Posts
%br

- @posts.each do |p|
  %strong Content
  %a= p.content
  %br
  %br

app/views/fun/index.html.haml
- @avatars.each do |a|
  %div.avatar-fun
    %strong Avatar
    %a= a.user_id
    %a= a.id
    %img{:src => a.src}

app/views/home/index.html.haml
%h2 Marketing Page

app/views/layouts/_header.html.haml
%header
  %div.fixed.top-bar-wrapper
    %nav.top-bar{'data-topbar' => true, role:'navigation'}
      %ul.title-area
        %li.name
          %h1= link_to "fumblr.", root_path
        %li.toggle-topbar.menu-icon
          %a{href:"#"}
            %span menu
      %section.top-bar-section
        %ul.right
          %li
            -# TODO: direct to explore page once we have that completed
            = link_to "explore", root_path
          %li
            -# TODO: direct to profile page once we have that completed
            = link_to "profile", root_path
          - if user_signed_in?
            %li
              = link_to "logout", destroy_user_session_path, method: :delete
          - else
            %li
              = link_to "login", new_user_session_path
            %li
              = link_to "signup", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "ustf-8"}    
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "fubmlr"
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  -# Render the header
  = render 'layouts/header'

  -# Add flash messages for Devise
  %p.notice= notice
  %p.alert= alert
  -# End of flash messages for Devise

  -# Render the body
  %body
    .main-content
      = yield

app/views/users/index.html.haml
%h2 Bunch-o-users
%ul
  - @users.each do |user|
    %li
      = image_tag user.avatar.src
      = "#{user.first_name}, #{user.last_name}"
      = user.email

app/views/users/prev-show.html.haml
%html

%body
  %div{:class => ['row', 'small-5 column']} 
    %ul{:class => ['small-block-grid-3']}
      = @informative_text
  .row
    .large-12.columns
      .panel
        %h1 Feed Template
  / End Header and Nav
  .row
    / Nav Sidebar
    / This is source ordered to be pulled to the left on larger screens
    .large-3.columns
      .panel
        %a{:href => "#"}
          %img{:src => "https://placekitten.com/g/300/240"}/
        %h5
          %a{:href => "#"} Your Name
        .section-container.vertical-nav{"data-options" => "deep_linking: false; one_up: true", "data-section" => ""}
          %section.section
            %h5.title
              %a{:href => "#"} friend 1
          %section.section
            %h5.title
              %a{:href => "#"} friend 2
          %section.section
            %h5.title
              %a{:href => "#"} friend 3
          %section.section
            %h5.title
              %a{:href => "#"} friend 4
          %section.section
            %h5.title
              %a{:href => "#"} friend 5
          %section.section
            %h5.title
              %a{:href => "#"} friend 6
    / Main Feed
    .large-6.columns
      / Feed Entry
      .row
        .large-2.columns.small-3
          %img{:src => "https://placekitten.com/g/80/80"}/
        .large-10.columns
          %p
            %strong Some Person said:
            Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .large-2.columns.small-3
              %img{:src => "https://placekitten.com/g/50/50"}/
            .large-10.columns
              %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit
          .row
            .large-2.columns.small-3
              %img{:src => "https://placekitten.com/g/50/50"}/
            .large-10.columns
              %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit
      / End Feed Entry
      %hr/
      / Feed Entry
      .row
        .large-2.columns.small-3
          %img{:src => "http://placehold.it/80x80&text=[img]"}/
        .large-10.columns
          %p
            %strong Some Person said:
            Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
      / End Feed Entry
      %hr/
      / Feed Entry
      .row
        .large-2.columns.small-3
          %img{:src => "http://placehold.it/80x80&text=[img]"}/
        .large-10.columns
          %p
            %strong Some Person said:
            Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.
          %ul.inline-list
            %li
              %a{:href => ""} Reply
            %li
              %a{:href => ""} Share
          %h6 2 Comments
          .row
            .large-2.columns.small-3
              %img{:src => "http://placehold.it/50x50&text=[img]"}/
            .large-10.columns
              %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit
      / End Feed Entry
    / Right Sidebar
    / On small devices this column is hidden
    %aside.large-3.columns.hide-for-small
      %p
        %img{:src => "https://placekitten.com/g/300/440"}/
      %p
        %img{:src => "https://placekitten.com/g/300/440"}/
  / Footer
  %footer.row
    .large-12.columns
      %hr/
      .row
        .large-5.columns
          %p &copy; Copyright FUMBLR
        .large-7.columns
          %ul.inline-list.right
            %li
              %a{:href => "#"} Section 1
            %li
              %a{:href => "#"} Section 2
            %li
              %a{:href => "#"} Section 3
            %li
              %a{:href => "#"} Section 4
            %li
              %a{:href => "#"} Section 5
            %li
              %a{:href => "#"} Section 6

app/views/users/show.html.haml
.row
  .medium-8.columns
    / Post
    - @posts.each do |post|
      .post
        .post-badge.avatar.left
          = image_tag post.user.avatar.src
        .post-content
          %strong
            = "#{post.user.first_name} #{post.user.last_name}:"
          = post.content
          .post-links.text-right
            = link_to "Follow", follow_user_user_path(@user, post.user), method: :post
            = link_to "Reply", root_path
          .comments
            - post.comments.each do |comment|
              .comment-item
                %small
                  = "#{comment.content} -#{comment.user.first_name} #{comment.user.last_name}"

  / Nav Sidebar
  / This is source ordered to be pulled to the right on larger screens
  .friend-list.medium-4.columns
    %h4
      = "I am following:"
    - @subscriptions.each do |following|
      .user-entry
        .avatar-sm.left
          = image_tag following.avatar.src
        = " | #{following.first_name} #{following.last_name}"
    %h4
      = "Following me:"
    - @subscribers.each do |following|
      .user-entry
        .avatar-sm.left
          = image_tag following.avatar.src
        = " | #{following.first_name} #{following.last_name}"

/ Footer
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-3.columns
        %p &copy; Copyright FUMBLR
      .large-5.columns
        %ul.inline-list.right
          %li
            %a{:href => "#"} Section 1
          %li
            %a{:href => "#"} Section 2
          %li
            %a{:href => "#"} Section 3
          %li
            %a{:href => "#"} Section 4
          %li
            %a{:href => "#"} Section 5
          %li
            %a{:href => "#"} Section 6